### ISSUE TITLE
x509

### ISSUE THREAD

**Issue by longxiaohan** [riba2534/openai-on-wechat#5]
[openai-on-wechat] 2023/03/13 23:50:31 handler.go:45: [text] Request: Hi
[openai-on-wechat] 2023/03/13 23:50:32 session.go:79: openAIClient.CreateChatCompletion err=Post "https://api.openai.com/v1/chat/completions": x509: certificate has expired or is not yet valid: current time 2023-03-13T23:50:32+08:00 is after 2021-09-30T14:01:15Z
[openai-on-wechat] 2023/03/13 23:50:32 handler.go:54: [text] Response: 抱歉，出错了，请稍后重试~

**Comment by riba2534** [comment]
证书问题，你解决了吗
